import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/**
 * One flat config for the whole workspace. `next lint` is deprecated and prompts
 * interactively, which cannot run in CI, so ESLint is invoked directly.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      'design/**',
      'content/**',
      'apps/web/next-env.d.ts', // generated by Next on every build
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      'no-console': 'off',
      eqeqeq: ['error', 'smart'],
    },
  },

  // Every colour comes from the token file; a hard-coded hex anywhere else means
  // the light theme, the dark theme, or both will drift
  // (features/00-design-system/CONTRACT.md).
  {
    files: ['packages/ui/**/*.{ts,tsx}', 'apps/web/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: "Literal[value=/#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\\b/]",
          message:
            'Couleur en dur : utilise un jeton de packages/ui/src/tokens.css (ex. bg-surface, var(--color-accent)).',
        },
        {
          selector: "TemplateElement[value.raw=/#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{3})\\b/]",
          message:
            'Couleur en dur : utilise un jeton de packages/ui/src/tokens.css (ex. bg-surface, var(--color-accent)).',
        },
      ],
    },
  },

  // The engine is pure by contract: no I/O, no ambient clock, no randomness. The
  // clock is always an input, which is what makes every rule testable
  // (features/09-learning-engine-core/CONTRACT.md).
  {
    files: ['packages/learning-engine/src/**/*.ts'],
    ignores: ['packages/learning-engine/src/**/*.test.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: "NewExpression[callee.name='Date'][arguments.length=0]",
          message: 'Le moteur ne lit pas l’horloge : passe `now` en paramètre.',
        },
        {
          selector: "MemberExpression[object.name='Date'][property.name='now']",
          message: 'Le moteur ne lit pas l’horloge : passe `now` en paramètre.',
        },
        {
          selector: "MemberExpression[object.name='Math'][property.name='random']",
          message: 'Le moteur est déterministe : passe une graine si tu as besoin d’aléa.',
        },
        {
          selector: "Identifier[name='process']",
          message: 'Le moteur n’accède ni au process ni à l’environnement.',
        },
        {
          selector: "CallExpression[callee.name='fetch']",
          message: 'Le moteur ne fait pas d’entrées-sorties.',
        },
        {
          selector: "ImportDeclaration[source.value=/^node:/]",
          message: 'Le moteur ne dépend pas des modules Node.',
        },
      ],
    },
  },

  // Tests describe behaviour; they may assert on literals the source must not carry.
  {
    files: ['**/*.{test,spec}.{ts,tsx}'],
    rules: { 'no-restricted-syntax': 'off', '@typescript-eslint/no-explicit-any': 'off' },
  },
);
